/**
 * Event tools — query and retrieve security events.
 *
 * Events are security detections (phishing, malware, DLP, anomaly, etc.)
 * generated by Checkpoint Harmony Email & Collaboration.
 */

import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { apiRequest } from "../utils/client.js";
import type { HecEvent, ApiResponse } from "../utils/types.js";
import type { CallToolResult } from "../utils/types.js";
import { formatPagedResult } from "../utils/format.js";

export const eventTools: Tool[] = [
  {
    name: "hec_query_events",
    description:
      "Query Checkpoint Harmony Email security events (phishing, malware, DLP, anomaly, shadow IT, etc.). Supports filtering by type, state, severity, date range, and SaaS platform. Returns events with available remediation actions.",
    inputSchema: {
      type: "object",
      properties: {
        eventTypes: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "phishing",
              "malware",
              "suspicious malware",
              "dlp",
              "anomaly",
              "shadow_it",
              "malicious_url_click",
              "malicious_url",
              "alert",
            ],
          },
          description: "Filter by event type(s)",
        },
        eventStates: {
          type: "array",
          items: {
            type: "string",
            enum: ["new", "detected", "pending", "remediated", "dismissed", "exception"],
          },
          description: "Filter by event state(s). Defaults to new/detected if omitted.",
        },
        severities: {
          type: "array",
          items: { type: "string" },
          description: "Filter by severity level(s) (e.g. Critical, High, Medium, Low)",
        },
        startDate: {
          type: "string",
          description: "Start date/time (ISO 8601, e.g. 2026-01-01T00:00:00Z)",
        },
        endDate: {
          type: "string",
          description: "End date/time (ISO 8601). Defaults to now.",
        },
        saas: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "email",
              "office365_emails",
              "office365_onedrive",
              "office365_sharepoint",
              "slack",
              "ms_teams",
              "google_mail",
              "box2",
              "dropbox2",
              "google_drive",
            ],
          },
          description: "Filter by SaaS platform(s)",
        },
        eventIds: {
          type: "array",
          items: { type: "string" },
          description: "Fetch specific event IDs",
        },
        scrollId: {
          type: "string",
          description: "Scroll ID for pagination (from previous response)",
        },
      },
    },
  },
  {
    name: "hec_get_event",
    description: "Get full details for a specific security event by ID.",
    inputSchema: {
      type: "object",
      properties: {
        eventId: { type: "string", description: "The event ID to retrieve" },
      },
      required: ["eventId"],
    },
  },
];

export async function handleEventTool(
  name: string,
  args: Record<string, unknown>
): Promise<CallToolResult> {
  if (name === "hec_query_events") {
    const requestData: Record<string, unknown> = {};
    if (args.eventTypes) requestData.eventTypes = args.eventTypes;
    if (args.eventStates) requestData.eventStates = args.eventStates;
    if (args.severities) requestData.severities = args.severities;
    if (args.startDate) requestData.startDate = args.startDate;
    if (args.endDate) requestData.endDate = args.endDate;
    if (args.saas) requestData.saas = args.saas;
    if (args.eventIds) requestData.eventIds = args.eventIds;
    if (args.scrollId) requestData.scrollId = args.scrollId;

    const result = await apiRequest<HecEvent>("/v1.0/event/query", {
      method: "POST",
      body: { requestData },
    });

    return formatResult(result, "events");
  }

  if (name === "hec_get_event") {
    const eventId = args.eventId as string;
    const result = await apiRequest<HecEvent>(`/v1.0/event/${encodeURIComponent(eventId)}`);
    return formatResult(result, "event");
  }

  throw new Error(`Unknown event tool: ${name}`);
}

function formatResult(result: ApiResponse<HecEvent>, label: string): CallToolResult {
  const summary = result.responseData.map((e) => ({
    eventId: e.eventId,
    type: e.type,
    state: e.state,
    severity: e.severity,
    saas: e.saas,
    eventCreated: e.eventCreated,
    description: e.description,
    confidenceIndicator: e.confidenceIndicator,
    availableActions: e.availableEventActions?.map((a) => a.actionName) ?? [],
  }));
  return formatPagedResult(result, summary, label);
}
